services:

  db:
    image: postgres
    container_name: loz_db_container
    shm_size: 128mb
    env_file:
      "./.env"
      
    volumes:
      - loz_db:/var/lib/postgresql/data/
  api:
    container_name: go_api_container
    build: ./backend/.
    ports:
      - 8080:8080
    depends_on: 
      - db
volumes:
  loz_db: